FROM resin/%%RESIN_MACHINE_NAME%%-node:8.5.0

ENV INITSYSTEM on

WORKDIR /usr/src/app

RUN npm install -g typescript

COPY package.json .

RUN JOBS=MAX npm install --unsafe-perm --production

COPY . ./

CMD rm -rf dist

RUN sh -c tsc

RUN node --check dist/app.js

CMD node dist/app.js