FROM resin/%%RESIN_MACHINE_NAME%%-node:8.5.0

ENV INITSYSTEM on

WORKDIR /usr/src/app

COPY package.json .

RUN JOBS=MAX npm install --unsafe-perm --production

COPY . ./

RUN JOBS=MAX npm run clean --unsafe-perm --production

RUN JOBS=MAX npm run build --unsafe-perm --production

RUN node --check dist/app.js

CMD node dist/app.js